spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanager}
    username: ${SPRING_DATASOURCE_USERNAME:artemsnyrev}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update      # auto-creates/updates tables from your entities
    show-sql: true          # logs SQL so you can see what Hibernate does
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:9upGEMMhF+oxhcDEVogayixXOvmk6by5mSF5i+XXtlE=}
  expiration: 3600000   # 1 hour, in milliseconds